import moment from 'moment';
import {Match} from './Models';

export const mockMatches: Match[] = [
  {
    id: 1,
    begin_at: moment().subtract(1, 'hour').toISOString(),
    detailed_stats: true,
    draw: false,
    end_at: null,
    forfeit: false,
    game_advantage: null,
    games: [],
    league: {
      id: 1,
      image_url: 'https://example.com/league-image.jpg',
      modified_at: moment().toISOString(),
      name: 'League',
      slug: 'league',
      url: null,
    },
    league_id: 1,
    live: {
      opens_at: null,
      supported: true,
      url: null,
    },
    match_type: 'type',
    modified_at: moment().toISOString(),
    name: 'Match 1',
    number_of_games: 2,
    opponents: [
      {
        opponent: {
          acronym: null,
          id: 2,
          image_url: 'https://example.com/team-image.jpg',
          location: 'Location',
          modified_at: moment().toISOString(),
          name: 'Team 1',
          slug: 'team1',
        },
        type: 'team',
      },
      {
        opponent: {
          acronym: null,
          id: 3,
          image_url: 'https://example.com/team-image.jpg',
          location: 'Location',
          modified_at: moment().toISOString(),
          name: 'Team 2',
          slug: 'team2',
        },
        type: 'team',
      },
    ],
    original_scheduled_at: moment().toISOString(),
    rescheduled: false,
    results: [
      {
        score: 3,
        team_id: 2,
      },
      {
        score: 2,
        team_id: 3,
      },
    ],
    scheduled_at: moment().toISOString(),
    serie: {
      begin_at: moment().toISOString(),
      end_at: null,
      full_name: 'Serie',
      id: 1,
      league_id: 1,
      modified_at: moment().toISOString(),
      name: 'Serie',
      season: null,
      slug: 'serie',
      winner_id: null,
      winner_type: null,
      year: 2023,
    },
    serie_id: 1,
    slug: 'match1',
    status: 'running',
    streams_list: [],
    tournament: {
      begin_at: moment().toISOString(),
      end_at: null,
      has_bracket: true,
      id: 1,
      league_id: 1,
      live_supported: true,
      modified_at: moment().toISOString(),
      name: 'Tournament',
      prizepool: null,
      serie_id: 1,
      slug: 'tournament',
      tier: 'tier',
      winner_id: null,
      winner_type: 'team',
    },
    tournament_id: 1,
    videogame: {
      id: 1,
      name: 'Game',
      slug: 'game',
    },
    videogame_version: null,
    winner: null,
    winner_id: null,
    winner_type: 'team',
  },
  {
    id: 2,
    begin_at: moment().add(1, 'hour').toISOString(),
    detailed_stats: false,
    draw: false,
    end_at: null,
    forfeit: false,
    game_advantage: null,
    games: [],
    league: {
      id: 2,
      image_url: 'https://example.com/league-image.jpg',
      modified_at: moment().toISOString(),
      name: 'League 2',
      slug: 'league2',
      url: null,
    },
    league_id: 2,
    live: {
      opens_at: null,
      supported: true,
      url: null,
    },
    match_type: 'type',
    modified_at: moment().toISOString(),
    name: 'Match 2',
    number_of_games: 3,
    opponents: [
      {
        opponent: {
          acronym: null,
          id: 4,
          image_url: 'https://example.com/team-image.jpg',
          location: 'Location',
          modified_at: moment().toISOString(),
          name: 'Team 3',
          slug: 'team3',
        },
        type: 'team',
      },
      {
        opponent: {
          acronym: null,
          id: 5,
          image_url: 'https://example.com/team-image.jpg',
          location: 'Location',
          modified_at: moment().toISOString(),
          name: 'Team 4',
          slug: 'team4',
        },
        type: 'team',
      },
    ],
    original_scheduled_at: moment().toISOString(),
    rescheduled: false,
    results: [],
    scheduled_at: moment().toISOString(),
    serie: {
      begin_at: moment().toISOString(),
      end_at: null,
      full_name: 'Serie 2',
      id: 2,
      league_id: 2,
      modified_at: moment().toISOString(),
      name: 'Serie 2',
      season: null,
      slug: 'serie2',
      winner_id: null,
      winner_type: null,
      year: 2023,
    },
    serie_id: 2,
    slug: 'match2',
    status: 'not_started',
    streams_list: [],
    tournament: {
      begin_at: moment().toISOString(),
      end_at: null,
      has_bracket: true,
      id: 2,
      league_id: 2,
      live_supported: true,
      modified_at: moment().toISOString(),
      name: 'Tournament 2',
      prizepool: null,
      serie_id: 2,
      slug: 'tournament2',
      tier: 'tier',
      winner_id: null,
      winner_type: 'team',
    },
    tournament_id: 2,
    videogame: {
      id: 2,
      name: 'Game 2',
      slug: 'game2',
    },
    videogame_version: null,
    winner: null,
    winner_id: null,
    winner_type: 'team',
  },
];

export const mockSortedData = [
  {
    id: 1,
    status: 'not_started',
    begin_at: moment().subtract(1, 'hours').toISOString(),
  },
  {
    id: 2,
    status: 'running',
    begin_at: moment().toISOString(),
  },
  {
    id: 3,
    status: 'running',
    begin_at: moment().subtract(2, 'hours').toISOString(),
  },
  {
    id: 4,
    status: 'not_started',
    begin_at: moment().add(4, 'hours').toISOString(),
  },
  {
    id: 5,
    status: 'not_started',
    begin_at: moment().add(4, 'days').toISOString(),
  },
  {
    id: 6,
    status: 'not_started',
    begin_at: moment().add(12, 'days').toISOString(),
  },
];
