import {Team} from './Models';

export const mockTeam: Team = {
  acronym: null,
  current_videogame: {
    id: 3,
    name: 'Videogame 3',
    slug: 'videogame-3',
  },
  id: 3,
  image_url: 'https://example.com/team3-image.jpg',
  location: 'Team Location 3',
  modified_at: '2022-01-03T00:00:00Z',
  name: 'Team Name 3',
  players: [
    {
      age: 26,
      birthday: '1996-08-20',
      first_name: 'Alex',
      id: 3,
      image_url: 'https://example.com/player3-image.jpg',
      last_name: 'Johnson',
      modified_at: '2022-01-03T00:00:00Z',
      name: 'Alex Johnson',
      nationality: 'USA',
      role: 'Player',
      slug: 'alex-johnson',
    },
    {
      age: 24,
      birthday: '1998-03-12',
      first_name: 'Sarah',
      id: 4,
      image_url: 'https://example.com/player4-image.jpg',
      last_name: 'Williams',
      modified_at: '2022-01-03T00:00:00Z',
      name: 'Sarah Williams',
      nationality: 'Canada',
      role: 'Player',
      slug: 'sarah-williams',
    },
    {
      age: 29,
      birthday: '1993-11-05',
      first_name: 'Michael',
      id: 5,
      image_url: 'https://example.com/player5-image.jpg',
      last_name: 'Brown',
      modified_at: '2022-01-03T00:00:00Z',
      name: 'Michael Brown',
      nationality: 'UK',
      role: 'Player',
      slug: 'michael-brown',
    },
    {
      age: 27,
      birthday: '1995-06-25',
      first_name: 'Emma',
      id: 6,
      image_url: 'https://example.com/player6-image.jpg',
      last_name: 'Davis',
      modified_at: '2022-01-03T00:00:00Z',
      name: 'Emma Davis',
      nationality: 'Australia',
      role: 'Player',
      slug: 'emma-davis',
    },
    {
      age: 23,
      birthday: '1999-02-08',
      first_name: 'Daniel',
      id: 7,
      image_url: 'https://example.com/player7-image.jpg',
      last_name: 'Wilson',
      modified_at: '2022-01-03T00:00:00Z',
      name: 'Daniel Wilson',
      nationality: 'USA',
      role: 'Player',
      slug: 'daniel-wilson',
    },
  ],
  slug: 'team-name-3',
};
